"use client"

import { useState, useEffect, useRef } from "react"

const LANGS = [
  { code: "en", label: "EN", name: "English" },
  { code: "es", label: "ES", name: "Español" },
  { code: "pt", label: "PT", name: "Português" },
  { code: "fr", label: "FR", name: "Français" },
  { code: "de", label: "DE", name: "Deutsch" },
  { code: "it", label: "IT", name: "Italiano" },
  { code: "ar", label: "AR", name: "العربية" },
]

const LANG: Record<string, any> = {
  es: {
    hero_tag: "Agencia de captación digital",
    hero_title_1: "Cazamos negocios",
    hero_title_2: "invisibles",
    hero_title_3: " y los sacamos a la luz",
    hero_desc: "Detectamos negocios locales sin web en España y Marruecos. Les construimos una presencia online profesional y los ponemos en el mapa. Sin que ellos levanten un dedo.",
    hero_cta_1: "Ver casos reales",
    hero_cta_2: "Recomendar un negocio",
    hero_cta_3: "Crea tu web gratis",
    scroll_hint: "Descubre cómo",
    nav_1: "Cómo funciona",
    nav_2: "Casos",
    nav_3: "Contacto",
    nav_4: "Crea tu web",
    how_title_1: "Cómo",
    how_title_2: "cazamos",
    how_title_3: " negocios",
    step_1_title: "Escaneamos el mapa",
    step_1_desc: "Rastreamos negocios locales sin web en España y Marruecos. Detectamos su ubicación, categoría y potencial digital.",
    step_2_title: "Creamos su web",
    step_2_desc: "Diseñamos y construimos una web profesional adaptada a su negocio. Moderna, rápida y lista para atraer clientes.",
    step_3_title: "Les contactamos",
    step_3_desc: "Enviamos un email mostrando la web ya creada. Solo tienen que decir sí. Nosotros hacemos el resto.",
    portfolio_title_1: "Antes y después",
    portfolio_title_2: "reales",
    portfolio_desc: "Negocios que encontramos sin presencia online y transformamos en pocos días.",
    portfolio_before: "Antes",
    portfolio_after: "Después",
    portfolio_tag: "Web generada por NOIRA",
    contact_title: "Recomiéndanos un negocio",
    contact_desc: "¿Conoces un negocio local sin web? Cuéntanos y lo cazamos. Te llevas una comisión cuando cierre el trato.",
    contact_thanks: "¡Gracias por la recomendación!",
    contact_thanks_desc: "Revisaremos el negocio y te contactaremos si es viable.",
    form_name: "Tu nombre",
    form_name_ph: "p. ej. María García",
    form_email: "Tu email",
    form_email_ph: "tu@email.com",
    form_business: "Negocio a recomendar",
    form_business_ph: "p. ej. Panadería San Miguel",
    form_info: "¿Dónde está? ¿Qué sabes de él?",
    form_info_ph: "Dirección, categoría, por qué crees que necesita web...",
    form_submit: "Enviar recomendación",
    form_sending: "Enviando...",
    footer: "Cazamos negocios invisibles.",
  },
  en: {
    hero_tag: "Digital Capture Agency",
    hero_title_1: "We hunt",
    hero_title_2: "invisible",
    hero_title_3: " businesses and bring them to light",
    hero_desc: "We detect local businesses without a website in Spain and Morocco. We build a professional online presence and put them on the map. Without them lifting a finger.",
    hero_cta_1: "See real cases",
    hero_cta_2: "Recommend a business",
    hero_cta_3: "Create your free website",
    scroll_hint: "Discover how",
    nav_1: "How it works",
    nav_2: "Cases",
    nav_3: "Contact",
    nav_4: "Create your site",
    how_title_1: "How we",
    how_title_2: "hunt",
    how_title_3: " businesses",
    step_1_title: "We scan the map",
    step_1_desc: "We track local businesses without a website in Spain and Morocco. We detect their location, category, and digital potential.",
    step_2_title: "We create their site",
    step_2_desc: "We design and build a professional website tailored to their business. Modern, fast, and ready to attract customers.",
    step_3_title: "We contact them",
    step_3_desc: "We send an email showing the already-created website. They just have to say yes. We do the rest.",
    portfolio_title_1: "Real before",
    portfolio_title_2: "and after",
    portfolio_desc: "Businesses we found without an online presence and transformed in days.",
    portfolio_before: "Before",
    portfolio_after: "After",
    portfolio_tag: "Website generated by NOIRA",
    contact_title: "Recommend a business",
    contact_desc: "Know a local business without a website? Tell us and we'll hunt them. You get a commission when the deal closes.",
    contact_thanks: "Thanks for the recommendation!",
    contact_thanks_desc: "We'll review the business and contact you if it's viable.",
    form_name: "Your name",
    form_name_ph: "e.g. John Smith",
    form_email: "Your email",
    form_email_ph: "you@email.com",
    form_business: "Business to recommend",
    form_business_ph: "e.g. San Miguel Bakery",
    form_info: "Where is it? What do you know?",
    form_info_ph: "Address, category, why do you think they need a website...",
    form_submit: "Send recommendation",
    form_sending: "Sending...",
    footer: "We hunt invisible businesses.",
  },
  fr: {
    hero_tag: "Agence de capture numérique",
    hero_title_1: "Nous chassons les",
    hero_title_2: "invisibles",
    hero_title_3: " et les révélons au grand jour",
    hero_desc: "Nous détectons les commerces locaux sans site web en Espagne et au Maroc. Nous leur créons une présence en ligne professionnelle et les mettons sur la carte.",
    hero_cta_1: "Voir des cas réels",
    hero_cta_2: "Recommander un commerce",
    hero_cta_3: "Créez votre site",
    scroll_hint: "Découvrez comment",
    nav_1: "Fonctionnement",
    nav_2: "Cas",
    nav_3: "Contact",
    nav_4: "Créez votre site",
    how_title_1: "Comment nous",
    how_title_2: "chassons",
    how_title_3: " les commerces",
    step_1_title: "Nous scannons la carte",
    step_1_desc: "Nous repérons les commerces locaux sans site web en Espagne et au Maroc.",
    step_2_title: "Nous créons leur site",
    step_2_desc: "Nous concevons un site web professionnel adapté à leur activité.",
    step_3_title: "Nous les contactons",
    step_3_desc: "Nous envoyons un email présentant le site déjà créé.",
    portfolio_title_1: "Avant et après",
    portfolio_title_2: "réels",
    portfolio_desc: "Des commerces que nous avons trouvés sans présence en ligne.",
    portfolio_before: "Avant",
    portfolio_after: "Après",
    portfolio_tag: "Site créé par NOIRA",
    contact_title: "Recommander un commerce",
    contact_desc: "Vous connaissez un commerce local sans site web ? Dites-le nous.",
    contact_thanks: "Merci !",
    contact_thanks_desc: "Nous examinerons le commerce et vous contacterons.",
    form_name: "Votre nom",
    form_name_ph: "ex. Marie",
    form_email: "Votre email",
    form_email_ph: "vous@email.com",
    form_business: "Commerce à recommander",
    form_business_ph: "ex. Boulangerie Saint-Michel",
    form_info: "Où se trouve-t-il ?",
    form_info_ph: "Adresse, catégorie...",
    form_submit: "Envoyer",
    form_sending: "Envoi...",
    footer: "Nous chassons les commerces invisibles.",
  },
  pt: {
    hero_tag: "Agência de captura digital",
    hero_title_1: "Caçamos negócios",
    hero_title_2: "invisíveis",
    hero_title_3: " e os trazemos à luz",
    hero_desc: "Detectamos negócios locais sem site na Espanha e Marrocos. Construímos uma presença online profissional.",
    hero_cta_1: "Ver casos reais",
    hero_cta_2: "Recomendar um negócio",
    hero_cta_3: "Crie seu site grátis",
    scroll_hint: "Descubra como",
    nav_1: "Como funciona",
    nav_2: "Casos",
    nav_3: "Contato",
    nav_4: "Crie seu site",
    how_title_1: "Como",
    how_title_2: "caçamos",
    how_title_3: " negócios",
    step_1_title: "Escaneamos o mapa",
    step_1_desc: "Rastreamos negócios locais sem site na Espanha e Marrocos.",
    step_2_title: "Criamos o site",
    step_2_desc: "Projetamos um site profissional adaptado ao negócio.",
    step_3_title: "Contatamos",
    step_3_desc: "Enviamos um email mostrando o site já criado.",
    portfolio_title_1: "Antes e depois",
    portfolio_title_2: "reais",
    portfolio_desc: "Negócios que encontramos sem presença online.",
    portfolio_before: "Antes",
    portfolio_after: "Depois",
    portfolio_tag: "Site gerado por NOIRA",
    contact_title: "Recomende um negócio",
    contact_desc: "Conhece um negócio local sem site? Conte-nos.",
    contact_thanks: "Obrigado!",
    contact_thanks_desc: "Revisaremos o negócio e entraremos em contato.",
    form_name: "Seu nome",
    form_name_ph: "ex. Maria",
    form_email: "Seu email",
    form_email_ph: "voce@email.com",
    form_business: "Negócio para recomendar",
    form_business_ph: "ex. Padaria São Miguel",
    form_info: "Onde fica?",
    form_info_ph: "Endereço, categoria...",
    form_submit: "Enviar",
    form_sending: "Enviando...",
    footer: "Caçamos negócios invisíveis.",
  },
  de: {
    hero_tag: "Digitale Erfassungsagentur",
    hero_title_1: "Wir jagen",
    hero_title_2: "unsichtbare",
    hero_title_3: " Unternehmen und bringen sie ans Licht",
    hero_desc: "Wir finden lokale Unternehmen ohne Website in Spanien und Marokko. Wir erstellen eine professionelle Online-Präsenz.",
    hero_cta_1: "Echte Fälle sehen",
    hero_cta_2: "Unternehmen empfehlen",
    hero_cta_3: "Erstellen Sie Ihre Website",
    scroll_hint: "Entdecken Sie wie",
    nav_1: "So funktioniert's",
    nav_2: "Fälle",
    nav_3: "Kontakt",
    nav_4: "Website erstellen",
    how_title_1: "Wie wir",
    how_title_2: "jagen",
    how_title_3: " Unternehmen",
    step_1_title: "Wir scannen die Karte",
    step_1_desc: "Wir finden lokale Unternehmen ohne Website in Spanien und Marokko.",
    step_2_title: "Wir erstellen die Website",
    step_2_desc: "Wir entwerfen eine professionelle Website für ihr Unternehmen.",
    step_3_title: "Wir kontaktieren sie",
    step_3_desc: "Wir senden eine E-Mail mit der bereits erstellten Website.",
    portfolio_title_1: "Vorher und",
    portfolio_title_2: "nachher",
    portfolio_desc: "Unternehmen ohne Online-Präsenz, die wir transformiert haben.",
    portfolio_before: "Vorher",
    portfolio_after: "Nachher",
    portfolio_tag: "Website erstellt von NOIRA",
    contact_title: "Empfehlen Sie ein Unternehmen",
    contact_desc: "Kennen Sie ein lokales Unternehmen ohne Website?",
    contact_thanks: "Danke!",
    contact_thanks_desc: "Wir prüfen das Unternehmen und melden uns.",
    form_name: "Ihr Name",
    form_name_ph: "z.B. Max Müller",
    form_email: "Ihre E-Mail",
    form_email_ph: "sie@email.com",
    form_business: "Zu empfehlendes Unternehmen",
    form_business_ph: "z.B. Bäckerei Schmidt",
    form_info: "Wo ist es?",
    form_info_ph: "Adresse, Kategorie...",
    form_submit: "Senden",
    form_sending: "Sende...",
    footer: "Wir jagen unsichtbare Unternehmen.",
  },
  it: {
    hero_tag: "Agenzia di cattura digitale",
    hero_title_1: "Cacciamo",
    hero_title_2: "invisibili",
    hero_title_3: " e li portiamo alla luce",
    hero_desc: "Rileviamo attività locali senza sito web in Spagna e Marocco. Creiamo una presenza online professionale.",
    hero_cta_1: "Vedi casi reali",
    hero_cta_2: "Raccomanda un'attività",
    hero_cta_3: "Crea il tuo sito gratis",
    scroll_hint: "Scopri come",
    nav_1: "Come funziona",
    nav_2: "Casi",
    nav_3: "Contatto",
    nav_4: "Crea il tuo sito",
    how_title_1: "Come",
    how_title_2: "cacciamo",
    how_title_3: " attività",
    step_1_title: "Scansioniamo la mappa",
    step_1_desc: "Troviamo attività locali senza sito web in Spagna e Marocco.",
    step_2_title: "Creiamo il sito",
    step_2_desc: "Progettiamo un sito web professionale su misura.",
    step_3_title: "Li contattiamo",
    step_3_desc: "Inviiamo un'email mostrando il sito già creato.",
    portfolio_title_1: "Prima e",
    portfolio_title_2: "dopo",
    portfolio_desc: "Attività trovate senza presenza online e trasformate.",
    portfolio_before: "Prima",
    portfolio_after: "Dopo",
    portfolio_tag: "Sito generato da NOIRA",
    contact_title: "Raccomanda un'attività",
    contact_desc: "Conosci un'attività locale senza sito web?",
    contact_thanks: "Grazie!",
    contact_thanks_desc: "Valuteremo l'attività e ti contatteremo.",
    form_name: "Il tuo nome",
    form_name_ph: "es. Marco Rossi",
    form_email: "La tua email",
    form_email_ph: "tuo@email.com",
    form_business: "Attività da raccomandare",
    form_business_ph: "es. Panetteria San Marco",
    form_info: "Dove si trova?",
    form_info_ph: "Indirizzo, categoria...",
    form_submit: "Invia",
    form_sending: "Invio...",
    footer: "Cacciamo attività invisibili.",
  },
  ar: {
    hero_tag: "وكالة الصيد الرقمي",
    hero_title_1: "نصطاد",
    hero_title_2: "الأنشطة",
    hero_title_3: " التجارية غير المرئية ونخرجها للنور",
    hero_desc: "نكتشف الأنشطة التجارية المحلية بدون موقع إلكتروني في إسبانيا والمغرب. نبني لها حضوراً رقمياً محترفاً.",
    hero_cta_1: "شاهد حالات حقيقية",
    hero_cta_2: "أوصِ بنشاط تجاري",
    hero_cta_3: "أنشئ موقعك مجاناً",
    scroll_hint: "اكتشف كيف",
    nav_1: "كيف يعمل",
    nav_2: "حالات",
    nav_3: "اتصل بنا",
    nav_4: "أنشئ موقعك",
    how_title_1: "كيف",
    how_title_2: "نصطاد",
    how_title_3: " الأنشطة",
    step_1_title: "نمسح الخريطة",
    step_1_desc: "نتتبع الأنشطة التجارية المحلية بدون موقع إلكتروني.",
    step_2_title: "ننشئ الموقع",
    step_2_desc: "نصمم موقعاً إلكترونياً محترفاً مناسباً لنشاطهم.",
    step_3_title: "نتصل بهم",
    step_3_desc: "نرسل بريداً إلكترونياً يظهر الموقع الذي تم إنشاؤه بالفعل.",
    portfolio_title_1: "قبل و",
    portfolio_title_2: "بعد",
    portfolio_desc: "أنشطة وجدناها بدون حضور إلكتروني وطورناها.",
    portfolio_before: "قبل",
    portfolio_after: "بعد",
    portfolio_tag: "موقع من إنشاء NOIRA",
    contact_title: "أوصِ بنشاط تجاري",
    contact_desc: "هل تعرف نشاطاً تجارياً محلياً بدون موقع إلكتروني؟",
    contact_thanks: "شكراً!",
    contact_thanks_desc: "سنراجع النشاط ونتصل بك.",
    form_name: "اسمك",
    form_name_ph: "مثال: محمد",
    form_email: "بريدك الإلكتروني",
    form_email_ph: "you@email.com",
    form_business: "النشاط التجاري",
    form_business_ph: "مثال: مخبز السلام",
    form_info: "أين يقع؟",
    form_info_ph: "العنوان، الفئة...",
    form_submit: "إرسال",
    form_sending: "جارٍ الإرسال...",
    footer: "نصطاد الأنشطة التجارية غير المرئية.",
  },
}

const portfolioCases = [
  { negocio: "Carnicería El Toro", ubicacion_es: "Málaga, España", ubicacion_fr: "Málaga, Espagne", antes_es: 'Sin web, solo recomendación boca a boca. Perdía clientes nuevos que buscaban "carnicería cerca de mí".', antes_fr: 'Sans site web, seulement le bouche à oreille. Perdait de nouveaux clients qui cherchaient "boucherie près de chez moi".', despues_es: "Web con carta, horarios y ubicación. +40% de consultas en el primer mes.", despues_fr: "Site avec carte, horaires et localisation. +40% de demandes le premier mois.", categoria: "Alimentación", categoria_fr: "Alimentation", pais: "ES" },
  { negocio: "Coiffure Amira", ubicacion_es: "Tánger, Marruecos", ubicacion_fr: "Tanger, Maroc", antes_es: "Sin presencia online. Clientes solo de paso, sin poder reservar cita online.", antes_fr: "Sans présence en ligne. Clients de passage seulement, sans pouvoir réserver en ligne.", despues_es: "Landing con galería de trabajos y botón de WhatsApp. +25 reservas/semana.", despues_fr: "Landing avec galerie de travaux et bouton WhatsApp. +25 réservations/semaine.", categoria: "Peluquería", categoria_fr: "Coiffure", pais: "MA" },
  { negocio: "Talleres Ramírez", ubicacion_es: "Granada, España", ubicacion_fr: "Grenade, Espagne", antes_es: "Dependía del teléfono. Sin web ni redes. Clientes jóvenes no lo encontraban.", antes_fr: "Dépendait du téléphone. Sans site ni réseaux. Les jeunes clients ne le trouvaient pas.", despues_es: "Web con presupuesto online, Google Maps y testimonios. +60% de clientes <35 años.", despues_fr: "Site avec devis en ligne, Google Maps et témoignages. +60% de clients <35 ans.", categoria: "Mecánica", categoria_fr: "Mécanique", pais: "ES" },
]

export default function Home() {
  const [form, setForm] = useState({ nombre: "", email: "", negocio: "", mensaje: "" })
  const [enviado, setEnviado] = useState(false)
  const [error, setError] = useState("")
  const [enviando, setEnviando] = useState(false)
  const [lang, setLang] = useState("en")
  const [langOpen, setLangOpen] = useState(false)
  const langRef = useRef<HTMLDivElement>(null)

  const langCodes = LANGS.map(l => l.code)

  useEffect(() => {
    const saved = localStorage.getItem("noira_lang")
    if (saved && langCodes.includes(saved)) { setLang(saved); return }
    const accept = navigator.language || ""
    const matched = langCodes.find(c => accept.startsWith(c))
    if (matched) setLang(matched)
    else setLang("en")
  }, [])

  useEffect(() => { localStorage.setItem("noira_lang", lang) }, [lang])

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (langRef.current && !langRef.current.contains(e.target as Node)) setLangOpen(false)
    }
    document.addEventListener("mousedown", handleClick)
    return () => document.removeEventListener("mousedown", handleClick)
  }, [])

  const t = LANG[lang as keyof typeof LANG]

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError("")
    setEnviando(true)
    try {
      const res = await fetch('/api/recomendar', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Error al enviar')
      setEnviado(true)
    } catch (err: any) {
      setError(err.message)
    } finally {
      setEnviando(false)
    }
  }

  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-noir-border/50 bg-noir-bg/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <span className="font-heading text-xl font-bold text-violeta">NOIRA</span>
          <div className="flex items-center gap-6">
            <nav className="flex gap-8 text-sm text-texto-muted">
              <a href="#como-funciona" className="hover:text-violeta transition-colors">{t.nav_1}</a>
              <a href="#casos" className="hover:text-violeta transition-colors">{t.nav_2}</a>
              <a href="#contacto" className="hover:text-violeta transition-colors">{t.nav_3}</a>
              <a href="/app/self-service" className="text-violeta font-medium hover:opacity-80 transition-colors">{t.nav_4}</a>
            </nav>
            <div className="relative font-mono text-xs" ref={langRef}>
              <button onClick={() => setLangOpen(!langOpen)} className="text-texto-muted hover:text-foreground transition-colors cursor-pointer px-2 py-1 border border-noir-border rounded">
                [{LANGS.find(l => l.code === lang)?.label || "EN"} ▾]
              </button>
              {langOpen && (
                <div className="absolute right-0 top-full mt-1 w-32 bg-[#111] border border-[#222] rounded-lg shadow-lg z-50 py-1">
                  {LANGS.map(l => (
                    <button key={l.code} onClick={() => { setLang(l.code); setLangOpen(false) }}
                      className={`w-full text-left px-3 py-1.5 text-xs hover:bg-[#222] transition-colors ${lang === l.code ? "text-[#39ff14]" : "text-[#666]"}`}>
                      [{l.label}] {l.name}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1">
        <section className="relative min-h-screen flex items-center justify-center overflow-hidden pt-16">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_#111111_0%,_#000000_70%)]" />
          <div className="relative z-10 max-w-6xl mx-auto px-6 flex flex-col lg:flex-row items-center gap-16 py-20">
            <div className="radar-container shrink-0" role="img" aria-label="Escáner de negocios sin web">
              <div className="radar-circle" /><div className="radar-circle" /><div className="radar-circle" /><div className="radar-circle" />
              <div className="radar-grid" /><div className="radar-sweep" /><div className="radar-dot" /><div className="radar-dot" /><div className="radar-dot" />
              <div className="radar-dot" /><div className="radar-dot" /><div className="radar-dot" /><div className="radar-dot" /><div className="radar-center" />
            </div>
            <div className="text-center lg:text-left max-w-xl">
              <p className="text-neon text-sm font-medium tracking-widest uppercase mb-4">{t.hero_tag}</p>
              <h1 className="font-heading text-4xl sm:text-5xl lg:text-6xl font-bold leading-tight mb-6">
                {t.hero_title_1} <span className="text-violeta">{t.hero_title_2}</span>{t.hero_title_3}
              </h1>
              <p className="text-texto-muted text-lg leading-relaxed mb-8">{t.hero_desc}</p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <a href="/app/self-service" className="inline-flex items-center justify-center px-8 py-3 rounded-lg font-bold" style={{ background: '#39ff14', color: '#000' }}>{t.hero_cta_3}</a>
                <a href="#casos" className="inline-flex items-center justify-center px-8 py-3 rounded-lg border border-noir-border text-texto-muted font-medium hover:border-violeta hover:text-violeta transition-colors">{t.hero_cta_1}</a>
                <a href="#contacto" className="inline-flex items-center justify-center px-8 py-3 rounded-lg border border-noir-border text-texto-muted font-medium hover:border-violeta hover:text-violeta transition-colors">{t.hero_cta_2}</a>
              </div>
            </div>
          </div>
          <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-texto-muted text-xs animate-bounce">
            <span>{t.scroll_hint}</span>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 3v10m0 0l-4-4m4 4l4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg>
          </div>
        </section>

        <section id="como-funciona" className="py-24 px-6">
          <div className="max-w-6xl mx-auto">
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-center mb-16">{t.how_title_1} <span className="text-violeta">{t.how_title_2}</span>{t.how_title_3}</h2>
            <div className="grid md:grid-cols-3 gap-8">
              {[
                { paso: "01", titulo_es: "Escaneamos el mapa", titulo_fr: "Nous scannons la carte", desc_es: "Rastreamos negocios locales sin web en España y Marruecos. Detectamos su ubicación, categoría y potencial digital.", desc_fr: "Nous repérons les commerces locaux sans site web en Espagne et au Maroc. Nous détectons leur emplacement, catégorie et potentiel numérique." },
                { paso: "02", titulo_es: "Creamos su web", titulo_fr: "Nous créons leur site", desc_es: "Diseñamos y construimos una web profesional adaptada a su negocio. Moderna, rápida y lista para atraer clientes.", desc_fr: "Nous concevons et construisons un site web professionnel adapté à leur activité. Moderne, rapide et prêt à attirer des clients." },
                { paso: "03", titulo_es: "Les contactamos", titulo_fr: "Nous les contactons", desc_es: "Enviamos un email mostrando la web ya creada. Solo tienen que decir sí. Nosotros hacemos el resto.", desc_fr: "Nous envoyons un email présentant le site déjà créé. Ils n'ont qu'à dire oui. Nous faisons le reste." },
              ].map((item) => (
                <div key={item.paso} className="p-8 rounded-xl border border-noir-border bg-noir-surface hover:border-violeta/50 transition-colors group">
                  <span className="font-heading text-4xl font-bold text-violeta/30 group-hover:text-violeta/60 transition-colors">{item.paso}</span>
                  <h3 className="font-heading text-xl font-semibold mt-4 mb-3">{lang === "es" ? item.titulo_es : item.titulo_fr}</h3>
                  <p className="text-texto-muted leading-relaxed">{lang === "es" ? item.desc_es : item.desc_fr}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section id="casos" className="py-24 px-6 border-t border-noir-border/50">
          <div className="max-w-6xl mx-auto">
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-center mb-4">{t.portfolio_title_1} <span className="text-violeta">{t.portfolio_title_2}</span></h2>
            <p className="text-texto-muted text-center max-w-xl mx-auto mb-16">{t.portfolio_desc}</p>
            <div className="grid md:grid-cols-3 gap-6">
              {portfolioCases.map((caso) => (
                <article key={caso.negocio} className="rounded-xl border border-noir-border bg-noir-surface overflow-hidden group">
                  <div className="p-6 space-y-4">
                    <div className="flex items-start justify-between">
                      <div>
                        <span className="text-xs font-medium text-neon uppercase tracking-wider">{lang === "es" ? caso.categoria : caso.categoria_fr}</span>
                        <h3 className="font-heading text-lg font-semibold mt-1">{caso.negocio}</h3>
                        <p className="text-xs text-texto-muted">{lang === "es" ? caso.ubicacion_es : caso.ubicacion_fr}</p>
                      </div>
                      <span className="text-xs px-2 py-1 rounded border border-noir-border text-texto-muted">{caso.pais === "ES" ? "🇪🇸 ES" : "🇲🇦 MA"}</span>
                    </div>
                    <div className="space-y-3">
                      <div className="p-3 rounded-lg bg-red-950/20 border border-red-900/30">
                        <p className="text-xs font-medium text-red-400 mb-1">{t.portfolio_before}</p>
                        <p className="text-sm text-texto-muted">{lang === "es" ? caso.antes_es : caso.antes_fr}</p>
                      </div>
                      <div className="p-3 rounded-lg bg-neon/5 border border-neon/20">
                        <p className="text-xs font-medium text-neon mb-1">{t.portfolio_after}</p>
                        <p className="text-sm text-texto">{lang === "es" ? caso.despues_es : caso.despues_fr}</p>
                      </div>
                    </div>
                  </div>
                  <div className="px-6 pb-6">
                    <div className="h-px bg-noir-border/50 mb-4" />
                    <div className="flex items-center gap-2 text-xs text-violeta">
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
                      <span>{t.portfolio_tag}</span>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section id="contacto" className="py-24 px-6 border-t border-noir-border/50">
          <div className="max-w-2xl mx-auto">
            <h2 className="font-heading text-3xl sm:text-4xl font-bold text-center mb-4">{t.contact_title}</h2>
            <p className="text-texto-muted text-center mb-12">{t.contact_desc}</p>
            {enviado ? (
              <div className="p-8 rounded-xl border border-neon/30 bg-neon/5 text-center">
                <p className="text-neon font-semibold text-lg mb-2">{t.contact_thanks}</p>
                <p className="text-texto-muted">{t.contact_thanks_desc}</p>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-5">
                <div className="grid sm:grid-cols-2 gap-5">
                  <div>
                    <label htmlFor="nombre" className="block text-sm font-medium text-texto-muted mb-2">{t.form_name}</label>
                    <input id="nombre" type="text" required value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} className="w-full px-4 py-3 rounded-lg bg-noir-surface border border-noir-border text-texto placeholder:text-texto-muted/50 focus:border-violeta focus:ring-1 focus:ring-violeta transition-colors" placeholder={t.form_name_ph} />
                  </div>
                  <div>
                    <label htmlFor="email" className="block text-sm font-medium text-texto-muted mb-2">{t.form_email}</label>
                    <input id="email" type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="w-full px-4 py-3 rounded-lg bg-noir-surface border border-noir-border text-texto placeholder:text-texto-muted/50 focus:border-violeta focus:ring-1 focus:ring-violeta transition-colors" placeholder={t.form_email_ph} />
                  </div>
                </div>
                <div>
                  <label htmlFor="negocio" className="block text-sm font-medium text-texto-muted mb-2">{t.form_business}</label>
                  <input id="negocio" type="text" required value={form.negocio} onChange={(e) => setForm({ ...form, negocio: e.target.value })} className="w-full px-4 py-3 rounded-lg bg-noir-surface border border-noir-border text-texto placeholder:text-texto-muted/50 focus:border-violeta focus:ring-1 focus:ring-violeta transition-colors" placeholder={t.form_business_ph} />
                </div>
                <div>
                  <label htmlFor="mensaje" className="block text-sm font-medium text-texto-muted mb-2">{t.form_info}</label>
                  <textarea id="mensaje" rows={4} value={form.mensaje} onChange={(e) => setForm({ ...form, mensaje: e.target.value })} className="w-full px-4 py-3 rounded-lg bg-noir-surface border border-noir-border text-texto placeholder:text-texto-muted/50 focus:border-violeta focus:ring-1 focus:ring-violeta transition-colors resize-none" placeholder={t.form_info_ph} />
                </div>
                {error && <p className="text-red-400 text-sm text-center">{error}</p>}
                <button type="submit" disabled={enviando} className="w-full py-3 px-8 rounded-lg bg-violeta text-white font-medium hover:bg-violeta/90 transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violeta disabled:opacity-50 disabled:cursor-not-allowed">{enviando ? t.form_sending : t.form_submit}</button>
              </form>
            )}
          </div>
        </section>
      </main>

      <footer className="border-t border-noir-border/50 py-8 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="font-heading text-sm font-bold text-violeta">NOIRA</span>
          <div className="flex gap-4 text-xs text-texto-muted">
            <a href="/terminos" className="hover:text-violeta transition-colors">Términos</a>
            <a href="/privacidad" className="hover:text-violeta transition-colors">Privacidad</a>
          </div>
          <p className="text-xs text-texto-muted">&copy; {new Date().getFullYear()} NOIRA. {t.footer}</p>
        </div>
      </footer>
    </>
  )
}
