import nodemailer from 'nodemailer'
import { GoogleGenerativeAI } from '@google/generative-ai'
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { LeadData } from './types'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '')

let _supabase: SupabaseClient | null = null
function getDb(): SupabaseClient {
  if (!_supabase) {
    _supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL || '',
      process.env.SUPABASE_SERVICE_ROLE_KEY || ''
    )
  }
  return _supabase
}

function getTransporter() {
  return nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    auth: {
      user: process.env.GMAIL_USER || 'noiramaster@gmail.com',
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  })
}

function buildBody(cuerpoOriginal: string): string {
  const direccion = process.env.DIRECCION_FISICA || 'Calle [Pendiente de registro]'
  const footer = `
---
Noira Webs — Cazamos negocios invisibles
${direccion}
noiramaster@gmail.com

Si no quieres recibir más emails, responde a este correo con "BAJA" en el asunto.
`
  return cuerpoOriginal.replace(/\[DIRECCIÓN FÍSICA DE NOIRA\]/g, direccion) + footer
}

async function sendEmailDirectly(leadId: string, emailId: string, asunto: string, cuerpo: string): Promise<void> {
  const destinatario = process.env.GMAIL_USER || 'noiramaster@gmail.com'

  const transporter = getTransporter()

  try {
    await transporter.sendMail({
      from: '"Noira Webs" <noiramaster@gmail.com>',
      to: destinatario,
      subject: asunto,
      text: buildBody(cuerpo),
    })

    const now = new Date().toISOString()

    await getDb()
      .from('emails')
      .update({ estado: 'enviado', fecha_enviado: now })
      .eq('id', emailId)

    await getDb()
      .from('leads')
      .update({ estado: 'contactado' })
      .eq('id', leadId)

    try {
      await getDb().rpc('incrementar_contador_envio')
    } catch { }

    console.log(`  ✓ Email SENT: "${asunto}" → ${destinatario}`)
  } catch (err: any) {
    // Send failed — mark as error so it can be retried from dashboard
    await getDb()
      .from('emails')
      .update({ estado: 'error_envio' })
      .eq('id', emailId)
    console.error(`  ✗ SMTP send failed: ${err.message}`)
  }
}

export async function generateEmailForLead(lead: LeadData): Promise<void> {
  console.log(`\n✉️  Generating email for: ${lead.nombre_negocio}`)

  const slug = lead.nombre_negocio
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)

  const webUrl = `https://noira-demos.vercel.app/cliente/${slug}`

  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

  const prompt = `Eres un asistente de ventas para NOIRA, una agencia que crea webs para negocios locales.

Genera un email corto y persuasivo para el dueño de "${lead.nombre_negocio}" (${lead.categoria} en ${lead.ubicacion}).
El idioma debe ser ${lead.idioma === 'fr' ? 'francés' : 'español'}.

Requisitos:
- MÁXIMO 1-2 emojis en todo el email
- Incluye este enlace a su web ya creada: ${webUrl}
- Incluye este enlace a la agencia NOIRA: https://noira-demos.vercel.app
- Incluye un texto de baja: "Si no quieres recibir más emails, responde BAJA"
- Remitente identificado: "NOIRA — Cazamos negocios invisibles"
- Tono cercano pero profesional
- Extensión máxima: 150 palabras

Responde SOLO con JSON:
{
  "asunto": "línea de asunto (máx 10 palabras)",
  "cuerpo": "cuerpo del email en texto plano"
}`

  let asunto: string
  let cuerpo: string

  try {
    const result = await model.generateContent(prompt)
    const text = result.response.text()

    const jsonMatch = text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No valid JSON in Gemini response')

    const email = JSON.parse(jsonMatch[0])
    asunto = email.asunto
    cuerpo = email.cuerpo
    console.log(`  Copy generated by AI: "${asunto}"`)
  } catch (err) {
    console.error(`  ✗ Gemini error: ${err}`)
    console.log('  Using fallback copy')

    asunto = `¿${lead.nombre_negocio} sin web? Te tenemos cubierto`
    cuerpo = `Hola,

Somos NOIRA, una agencia que ayuda a negocios locales como ${lead.nombre_negocio} a tener presencia online.

Hemos preparado una web profesional para ti:
${webUrl}

Es gratis y sin compromiso. Solo tienes que decirnos si quieres publicarla.

Más info: https://noira-demos.vercel.app

[DIRECCIÓN FÍSICA DE NOIRA]
Si no quieres recibir más emails, responde BAJA

Un saludo,
NOIRA`
  }

  // Check daily limit before sending
  let canSend = true
  try {
    const { data: config } = await getDb().from('config_envio').select('limite_diario_actual, emails_enviados_hoy').eq('id', 1).single()
    if (config && config.emails_enviados_hoy >= config.limite_diario_actual) {
      console.log(`  ⚠ Daily limit reached (${config.emails_enviados_hoy}/${config.limite_diario_actual}). Saving as borrador.`)
      canSend = false
    }
  } catch {
    canSend = false
  }

  // Save to DB
  const estado = canSend ? 'enviado' : 'borrador'
  const { error, data } = await getDb().from('emails').insert({
    lead_id: lead.id,
    asunto,
    cuerpo,
    estado,
    fecha_enviado: canSend ? new Date().toISOString() : null,
  }).select().single()

  if (error) {
    console.error(`  ✗ Supabase error: ${error.message}`)
    return
  }

  const emailId = data.id
  console.log(`  ✓ Email saved${canSend ? ' and queued for send' : ' (borrador — limit full)'}: "${asunto}"`)

  // Send immediately if within limit
  if (canSend) {
    await sendEmailDirectly(lead.id, emailId, asunto, cuerpo)
  }
}
