import nodemailer from 'nodemailer'
import { GoogleGenerativeAI } from '@google/generative-ai'
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { LeadData } from './types'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '')

let _supabase: SupabaseClient | null = null
function getDb(): SupabaseClient {
  if (!_supabase) {
    _supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL || '',
      process.env.SUPABASE_SERVICE_ROLE_KEY || ''
    )
  }
  return _supabase
}

function getTransporter() {
  return nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    auth: {
      user: process.env.GMAIL_USER || 'noiramaster@gmail.com',
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  })
}

function buildBody(cuerpoOriginal: string, idioma: string = 'es'): string {
  const direccion = process.env.DIRECCION_FISICA || 'Ferrol, 15404, España'
  const footer = idioma === 'fr'
    ? `\n---\nNoira Webs — Nous chassons les commerces invisibles\n${direccion}\nnoiramaster@gmail.com\n\nSi vous ne souhaitez plus recevoir d'emails, répondez "BAJA" à cet email.\n`
    : `\n---\nNoira Webs — Cazamos negocios invisibles\n${direccion}\nnoiramaster@gmail.com\n\nSi no quieres recibir más emails, responde a este correo con "BAJA" en el asunto.\n`
  return cuerpoOriginal + footer
}

async function sendEmailDirectly(leadId: string, emailId: string, asunto: string, cuerpo: string, idioma: string = 'es'): Promise<void> {
  const destinatario = process.env.GMAIL_USER || 'noiramaster@gmail.com'

  const transporter = getTransporter()

  try {
    await transporter.sendMail({
      from: '"Noira Webs" <noiramaster@gmail.com>',
      to: destinatario,
      subject: asunto,
      text: buildBody(cuerpo, idioma),
    })

    const now = new Date().toISOString()

    await getDb()
      .from('emails')
      .update({ estado: 'enviado', fecha_enviado: now })
      .eq('id', emailId)

    await getDb()
      .from('leads')
      .update({ estado: 'contactado' })
      .eq('id', leadId)

    try {
      await getDb().rpc('incrementar_contador_envio')
    } catch { }

    console.log(`  ✓ Email SENT: "${asunto}" → ${destinatario}`)
  } catch (err: any) {
    // Send failed — mark as error so it can be retried from dashboard
    await getDb()
      .from('emails')
      .update({ estado: 'error_envio' })
      .eq('id', emailId)
    console.error(`  ✗ SMTP send failed: ${err.message}`)
  }
}

export async function generateEmailForLead(lead: LeadData): Promise<void> {
  console.log(`\n✉️  Generating email for: ${lead.nombre_negocio}`)

  const slug = lead.nombre_negocio
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)

  const webUrl = `https://noira-demos.vercel.app/cliente/${slug}`

  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

  const prompt = `Eres un asistente de ventas para NOIRA, una agencia que crea webs para negocios locales.

Genera un email corto y persuasivo para el dueño de "${lead.nombre_negocio}" (${lead.categoria} en ${lead.ubicacion}).
El idioma debe ser ${lead.idioma === 'fr' ? 'francés' : 'español'}.

Requisitos:
- Asunto profesional y claro, sin sonar a vendedor agresivo
- MÁXIMO 1-2 emojis en todo el email
- Explica que ya tienen una web profesional creada y pueden verla gratis 7 días
- Menciona claramente que después son 19€/mes para mantenerla activa, sin permanencia
- Incluye este enlace a su web ya creada: ${webUrl}
- Incluye este enlace a la agencia NOIRA: https://noira-demos.vercel.app
- NO incluyas dirección física ni texto de baja — eso va en el pie automático
- Remitente: "NOIRA — Cazamos negocios invisibles"
- Tono cercano pero profesional
- Extensión máxima: 150 palabras

Responde SOLO con JSON:
{
  "asunto": "línea de asunto (máx 10 palabras)",
  "cuerpo": "cuerpo del email en texto plano"
}`

  let asunto: string
  let cuerpo: string

  try {
    const result = await model.generateContent(prompt)
    const text = result.response.text()

    const jsonMatch = text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No valid JSON in Gemini response')

    const email = JSON.parse(jsonMatch[0])
    asunto = email.asunto
    cuerpo = email.cuerpo
    console.log(`  Copy generated by AI: "${asunto}"`)
  } catch (err) {
    console.error(`  ✗ Gemini error: ${err}`)
    console.log('  Using fallback copy')

    if (lead.idioma === 'fr') {
      asunto = `Votre nouveau site web pour ${lead.nombre_negocio} est prêt`
      cuerpo = `Bonjour ${lead.nombre_negocio},

Nous avons créé un site web professionnel pour votre commerce. Vous pouvez le voir ici :
${webUrl}

Ce site est entièrement gratuit pendant 7 jours. Après cette période, il reste actif pour seulement 19€/mois (sans engagement, vous pouvez résilier quand vous voulez).

👉 Voir votre site : ${webUrl}
👉 Activer votre abonnement dès maintenant : https://noira-demos.vercel.app

Si vous avez la moindre question, répondez simplement à cet email.

L'équipe NOIRA


Plus d'infos : https://noira-demos.vercel.app`
    } else {
      asunto = `Tu nueva web para ${lead.nombre_negocio} ya está lista`
      cuerpo = `Hola ${lead.nombre_negocio},

Hemos creado una web profesional para tu negocio. Puedes verla aquí:
${webUrl}

Esta web es completamente gratis durante 7 días. Después, se mantiene activa por solo 19€/mes (sin permanencia, cancelas cuando quieras).

👉 Ver tu web: ${webUrl}
👉 Activar tu suscripción ya: https://noira-demos.vercel.app

Si tienes cualquier duda, responde a este email.

Un saludo,
El equipo de NOIRA


Más info: https://noira-demos.vercel.app`
    }
  }

  // Check daily limit before sending
  let canSend = true
  try {
    const { data: config } = await getDb().from('config_envio').select('limite_diario_actual, emails_enviados_hoy').eq('id', 1).single()
    if (config && config.emails_enviados_hoy >= config.limite_diario_actual) {
      console.log(`  ⚠ Daily limit reached (${config.emails_enviados_hoy}/${config.limite_diario_actual}). Saving as borrador.`)
      canSend = false
    }
  } catch {
    canSend = false
  }

  // Save to DB
  const estado = canSend ? 'enviado' : 'borrador'
  const { error, data } = await getDb().from('emails').insert({
    lead_id: lead.id,
    asunto,
    cuerpo,
    estado,
    fecha_enviado: canSend ? new Date().toISOString() : null,
  }).select().single()

  if (error) {
    console.error(`  ✗ Supabase error: ${error.message}`)
    return
  }

  const emailId = data.id
  console.log(`  ✓ Email saved${canSend ? ' and queued for send' : ' (borrador — limit full)'}: "${asunto}"`)

  // Send immediately if within limit
  if (canSend) {
    await sendEmailDirectly(lead.id, emailId, asunto, cuerpo, lead.idioma || 'es')
  }
}
