import nodemailer from 'nodemailer'
import { GoogleGenerativeAI } from '@google/generative-ai'
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { LeadData } from './types'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '')

let _supabase: SupabaseClient | null = null
function getDb(): SupabaseClient {
  if (!_supabase) {
    _supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL || '',
      process.env.SUPABASE_SERVICE_ROLE_KEY || ''
    )
  }
  return _supabase
}

function getTransporter() {
  return nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    auth: {
      user: process.env.GMAIL_USER || 'noiramaster@gmail.com',
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  })
}

function buildBody(cuerpoOriginal: string, idioma: string = 'es'): string {
  const direccion = process.env.DIRECCION_FISICA || 'Ferrol, 15404, España'
  const footer = idioma === 'fr'
    ? `\n---\nNoira Webs — Nous chassons les commerces invisibles\n${direccion}\nnoiramaster@gmail.com\n\nSi vous ne souhaitez plus recevoir d'emails, répondez "BAJA" à cet email.\n`
    : `\n---\nNoira Webs — Cazamos negocios invisibles\n${direccion}\nnoiramaster@gmail.com\n\nSi no quieres recibir más emails, responde a este correo con "BAJA" en el asunto.\n`
  return cuerpoOriginal + footer
}

async function sendEmailDirectly(leadId: string, emailId: string, asunto: string, cuerpo: string, idioma: string = 'es'): Promise<void> {
  const destinatario = process.env.GMAIL_USER || 'noiramaster@gmail.com'

  const transporter = getTransporter()

  try {
    await transporter.sendMail({
      from: '"Noira Webs" <noiramaster@gmail.com>',
      to: destinatario,
      subject: asunto,
      text: buildBody(cuerpo, idioma),
    })

    const now = new Date().toISOString()

    await getDb()
      .from('emails')
      .update({ estado: 'enviado', fecha_enviado: now })
      .eq('id', emailId)

    await getDb()
      .from('leads')
      .update({ estado: 'contactado' })
      .eq('id', leadId)

    try {
      await getDb().rpc('incrementar_contador_envio')
    } catch (counterErr: any) {
      console.error(`  ⚠ Failed to increment email counter: ${counterErr.message || counterErr}`)
    }

    console.log(`  ✓ Email SENT: "${asunto}" → ${destinatario}`)
  } catch (err: any) {
    // Send failed — mark as error so it can be retried from dashboard
    await getDb()
      .from('emails')
      .update({ estado: 'error_envio' })
      .eq('id', emailId)
    console.error(`  ✗ SMTP send failed: ${err.message}`)
  }
}

export async function generateEmailForLead(lead: LeadData): Promise<void> {
  console.log(`\n✉️  Generating email for: ${lead.nombre_negocio}`)

  const slug = lead.nombre_negocio
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)

  const webUrl = `https://noira-demos.vercel.app/cliente/${slug}`

  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

  const prompt = `Eres un asistente de ventas para NOIRA, una agencia que crea webs para negocios locales.

Genera un email corto y persuasivo para el dueño de "${lead.nombre_negocio}" (${lead.categoria} en ${lead.ubicacion}).
El idioma debe ser ${lead.idioma === 'fr' ? 'francés' : 'español'}.

Requisitos:
- Asunto profesional y claro, sin sonar a vendedor agresivo
- MÁXIMO 1-2 emojis en todo el email
- Invítalos a crear su web gratis en nuestra herramienta self-service: https://noira-smoky.vercel.app/app/self-service
- Pueden elegir estilo, servicios y contenido ellos mismos con total libertad
- Menciona que es gratis 7 días, luego 19€/mes sin permanencia
- NO incluyas dirección física ni texto de baja — eso va en el pie automático
- Remitente: "NOIRA — Cazamos negocios invisibles"
- Tono cercano pero profesional
- Extensión máxima: 150 palabras

Responde SOLO con JSON:
{
  "asunto": "línea de asunto (máx 10 palabras)",
  "cuerpo": "cuerpo del email en texto plano"
}`

  let asunto: string
  let cuerpo: string

  try {
    const result = await model.generateContent(prompt)
    const text = result.response.text()

    const jsonMatch = text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No valid JSON in Gemini response')

    const email = JSON.parse(jsonMatch[0])
    asunto = email.asunto
    cuerpo = email.cuerpo
    console.log(`  Copy generated by AI: "${asunto}"`)
  } catch (err) {
    console.error(`  ✗ Gemini error: ${err}`)
    console.log('  Using fallback copy')

    if (lead.idioma === 'fr') {
      asunto = `Créez votre site web ${lead.nombre_negocio} en 2 minutes`
      cuerpo = `Bonjour ${lead.nombre_negocio},

Vous pouvez créer et voir votre site web ici gratuitement, en choisissant tout vous-même en toute liberté :
https://noira-smoky.vercel.app/app/self-service

Notre outil vous guide pas à pas : choisissez votre style, vos services, et obtenez un site professionnel en un clic.

👉 Créer votre site : https://noira-smoky.vercel.app/app/self-service

C'est entièrement gratuit pendant 7 jours, puis 19€/mois pour rester actif (sans engagement).

Si vous avez la moindre question, répondez à cet email.

L'équipe NOIRA`
    } else {
      asunto = `Crea tu web para ${lead.nombre_negocio} en 2 minutos`
      cuerpo = `Hola ${lead.nombre_negocio},

Puedes crear y ver tu web aquí gratis, eligiendo todo tú con total libertad:
https://noira-smoky.vercel.app/app/self-service

Nuestra herramienta te guía paso a paso: elige tu estilo, tus servicios, y obtén una web profesional en un clic.

👉 Crear tu web: https://noira-smoky.vercel.app/app/self-service

Es completamente gratis durante 7 días, luego 19€/mes para mantenerla activa (sin permanencia).

Si tienes cualquier duda, responde a este email.

Un saludo,
El equipo de NOIRA`
    }
  }

  // Check daily limit before sending
  let canSend = true
  try {
    const { data: config } = await getDb().from('config_envio').select('fecha_ultimo_reset, limite_diario_actual, emails_enviados_hoy').eq('id', 1).single()
    if (config) {
      const today = new Date().toISOString().split('T')[0]
      if (config.fecha_ultimo_reset !== today) {
        await getDb().from('config_envio').update({ emails_enviados_hoy: 0, fecha_ultimo_reset: today, updated_at: new Date().toISOString() }).eq('id', 1)
        config.emails_enviados_hoy = 0
      }
      if (config.emails_enviados_hoy >= config.limite_diario_actual) {
        console.log(`  ⚠ Daily limit reached (${config.emails_enviados_hoy}/${config.limite_diario_actual}). Saving as borrador.`)
        canSend = false
      }
    }
  } catch (limitErr: any) {
    console.error(`  ⚠ Failed to check email limit: ${limitErr.message || limitErr}`)
    canSend = false
  }

  // Save to DB
  const estado = canSend ? 'enviado' : 'borrador'
  const { error, data } = await getDb().from('emails').insert({
    lead_id: lead.id,
    asunto,
    cuerpo,
    estado,
    fecha_enviado: canSend ? new Date().toISOString() : null,
  }).select().single()

  if (error) {
    console.error(`  ✗ Supabase error: ${error.message}`)
    return
  }

  const emailId = data.id
  console.log(`  ✓ Email saved${canSend ? ' and queued for send' : ' (borrador — limit full)'}: "${asunto}"`)

  // Send immediately if within limit
  if (canSend) {
    await sendEmailDirectly(lead.id, emailId, asunto, cuerpo, lead.idioma || 'es')
  }
}
